name: 'OCA/queue Upstream Sync'

on:
  schedule:
    - cron:  '0 7 * * 1,4'

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "OCA/queue"
          source_branch: "14.0"
          destination_repo: "cibex/queue"
          destination_branch: "14.0"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
